env:
  global:
    - COMMIT=${TRAVIS_COMMIT::6}
    - REPO=mayadataio/e2e-metrics
sudo: required
services:
- docker
script:
- docker build -t $REPO:ci . ;
- docker build -t $REPO:$COMMIT . ;
after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then 
    docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" && docker push $REPO:ci && docker push $REPO:$COMMIT; 
  fi