apiVersion: v1
kind: ServiceAccount
metadata:
  name: e2e-metrics
  namespace: e2e-metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: e2e-metrics
rules:
- apiGroups:
  - "*"
  resources:
  - namespaces
  verbs:
  - "*"
- apiGroups:
  - "*"
  resources:
  - pipelinecoverages
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: e2e-metrics
subjects:
- kind: ServiceAccount
  name: e2e-metrics
  namespace: e2e-metrics
roleRef:
  kind: ClusterRole
  name: e2e-metrics
  apiGroup: rbac.authorization.k8s.io
---